version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  # Bump dockerfile FROM
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7

  # Python package requirements
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 7

  # Pre-commit
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit:
        patterns:
          - "*"
    cooldown:
      default-days: 7
